import { mkdtemp, readFile, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';

import { afterEach, beforeEach, describe, expect, it } from 'vitest';

import { LOCAL_UPLOAD_PREFIX, LocalStorageAdapter } from './local-storage.adapter';
import type { StorageOptions } from './storage.options';

const KEY = 'uploads/019dd1a5-9235-70db-8d57-54ef901d8185/photo';
const PNG_HEADER = Buffer.from([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a]);

describe('LocalStorageAdapter', () => {
  let root: string;
  let adapter: LocalStorageAdapter;

  beforeEach(async () => {
    root = await mkdtemp(join(tmpdir(), 'local-storage-'));
    adapter = new LocalStorageAdapter(optionsFor(root));
  });

  afterEach(async () => {
    await rm(root, { recursive: true, force: true });
  });

  function optionsFor(localRoot: string): StorageOptions {
    return {
      driver: 'local',
      bucket: 'app-uploads',
      region: 'us-east-1',
      endpoint: 'http://unused',
      accessKeyId: 'unused',
      secretAccessKey: 'a-secret-that-signs-the-upload-token',
      forcePathStyle: true,
      localRoot,
    };
  }

  it('hands back a relative URL and a token that proves this server issued it', async () => {
    const policy = await adapter.createPresignedUpload({
      key: KEY,
      contentType: 'image/png',
      sizeBytes: PNG_HEADER.length,
      expiresInSeconds: 900,
    });

    expect(policy.url).toBe(`${LOCAL_UPLOAD_PREFIX}/app-uploads/${KEY}`);
    expect(policy.method).toBe('PUT');
    expect(policy.headers['x-upload-token']).toBe(adapter.tokenFor(KEY));
    expect(policy.expiresAt.getTime()).toBeGreaterThan(Date.now());
  });

  it('issues a different token per key, so one URL does not authorise another', () => {
    expect(adapter.tokenFor(KEY)).not.toBe(adapter.tokenFor(`${KEY}-other`));
  });

  it('stores bytes and reads back the facts confirm needs', async () => {
    await adapter.putObject(KEY, PNG_HEADER);

    await expect(adapter.headObject(KEY)).resolves.toEqual({
      sizeBytes: PNG_HEADER.length,
      contentType: null,
    });
    await expect(adapter.getObjectRange(KEY, 4)).resolves.toEqual(PNG_HEADER.subarray(0, 4));
  });

  it('reports a missing object as absent rather than throwing', async () => {
    await expect(adapter.headObject('uploads/never-written')).resolves.toBeNull();
    await expect(adapter.getObjectRange('uploads/never-written', 8)).resolves.toBeNull();
  });

  it('removes an object, and removing it twice is not an error', async () => {
    await adapter.putObject(KEY, PNG_HEADER);
    await adapter.deleteObject(KEY);
    await adapter.deleteObject(KEY);

    await expect(adapter.headObject(KEY)).resolves.toBeNull();
  });

  it('refuses a key that would escape the storage root', async () => {
    // The key is generated by this application, but treating it as trusted is
    // how a traversal becomes an arbitrary file write.
    await expect(adapter.putObject('../../escaped', PNG_HEADER)).rejects.toThrow(
      'outside the storage root',
    );
    await expect(readFile(join(root, '..', 'escaped'))).rejects.toThrow();
  });
});
